name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"    # 00:00 UTC
    - cron: "0 12 * * *"   # 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LeoFernandes210798
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub (output branch)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: output
          build_dir: dist
          jekyll: false
